name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
